import type { BiteTrailCurrency } from "@/lib/bite-trail";

export type BiteTrailOwnerKind = "you" | "friend";
export type BiteTrailCuisineGenre =
  | "cafe"
  | "Chinese"
  | "dessert"
  | "fast food"
  | "hawker"
  | "Indian"
  | "Japanese"
  | "Korean"
  | "Malay"
  | "Others"
  | "seafood"
  | "Thai"
  | "western";

export type BiteTrailFoodEntry = {
  comments: string;
  costPerPerson: number;
  currency: BiteTrailCurrency;
  cuisineGenre: BiteTrailCuisineGenre;
  id: string;
  itemsBought?: string;
  latitude: number;
  longitude: number;
  neighborhood: string;
  ownerKind: BiteTrailOwnerKind;
  ownerName: string;
  placeName: string;
  placeId?: string;
  ratingOutOf10: number;
  visitedAt: string;
};

export type BiteTrailPlace = {
  averageCost: number;
  averageRating: number;
  cuisineGenre: BiteTrailCuisineGenre;
  currency: BiteTrailCurrency;
  id: string;
  latitude: number;
  longitude: number;
  neighborhood: string;
  placeName: string;
  visits: BiteTrailFoodEntry[];
};

const rawMockFoodEntries: BiteTrailFoodEntry[] = [
  {
    id: "bt-maxwell-tian-tian",
    placeName: "Tian Tian Chicken Rice",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.2807,
    longitude: 103.8447,
    neighborhood: "Maxwell",
    costPerPerson: 6.5,
    currency: "SGD",
    cuisineGenre: "hawker",
    itemsBought: "Chicken rice, iced barley",
    ratingOutOf10: 9,
    visitedAt: "2026-06-14",
    comments:
      "Reliable lunch stop. Rice is fragrant and the queue moves faster than expected.",
  },
  {
    id: "bt-maxwell-zhen-zhen",
    placeName: "Zhen Zhen Porridge",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.28095,
    longitude: 103.84435,
    neighborhood: "Maxwell",
    costPerPerson: 5.8,
    currency: "SGD",
    cuisineGenre: "hawker",
    itemsBought: "Century egg porridge",
    ratingOutOf10: 8,
    visitedAt: "2026-06-02",
    comments:
      "Comfort food texture, best when eaten early before the stall gets too crowded.",
  },
  {
    id: "bt-maxwell-fuzhou",
    placeName: "Fuzhou Oyster Cake",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.28046,
    longitude: 103.84418,
    neighborhood: "Maxwell",
    costPerPerson: 3.2,
    currency: "SGD",
    cuisineGenre: "hawker",
    itemsBought: "Oyster cake",
    ratingOutOf10: 8,
    visitedAt: "2026-05-29",
    comments: "Crispy snack pin from Kai's list. Worth adding as a side stop.",
  },
  {
    id: "bt-tanjong-pagar-bakery",
    placeName: "Keong Saik Bakery",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.28021,
    longitude: 103.84222,
    neighborhood: "Tanjong Pagar",
    costPerPerson: 12,
    currency: "SGD",
    cuisineGenre: "dessert",
    itemsBought: "Sourdough tart, coffee",
    ratingOutOf10: 8,
    visitedAt: "2026-05-18",
    comments:
      "Good dessert follow-up after dinner nearby. The pastry case is the main draw.",
  },
  {
    id: "bt-bugis-albert-kway-chap",
    placeName: "Albert Centre Kway Chap",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.30084,
    longitude: 103.85416,
    neighborhood: "Bugis",
    costPerPerson: 7.4,
    currency: "SGD",
    cuisineGenre: "hawker",
    itemsBought: "Kway chap set",
    ratingOutOf10: 8,
    visitedAt: "2026-04-27",
    comments: "Strong weekday option when in Bugis. Broth was the highlight.",
  },
  {
    id: "bt-bugis-dessert",
    placeName: "Ah Chew Desserts",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.30051,
    longitude: 103.85554,
    neighborhood: "Bugis",
    costPerPerson: 6.8,
    currency: "SGD",
    cuisineGenre: "dessert",
    itemsBought: "Mango sago, sesame paste",
    ratingOutOf10: 8,
    visitedAt: "2026-04-20",
    comments:
      "Late-night dessert pin. Best as a shared stop because portions are generous.",
  },
  {
    id: "bt-holland-village-pasta",
    placeName: "Tipo Pasta Bar",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.31113,
    longitude: 103.79589,
    neighborhood: "Holland Village",
    costPerPerson: 22,
    currency: "SGD",
    cuisineGenre: "western",
    itemsBought: "Pink sauce pasta, iced tea",
    ratingOutOf10: 9,
    visitedAt: "2026-03-09",
    comments:
      "More expensive than hawker pins, but the handmade pasta made it memorable.",
  },
  {
    id: "bt-jewel-ramen",
    placeName: "Tsuta Jewel",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.36021,
    longitude: 103.98974,
    neighborhood: "Changi",
    costPerPerson: 19.5,
    currency: "SGD",
    cuisineGenre: "Japanese",
    itemsBought: "Shoyu soba",
    ratingOutOf10: 8,
    visitedAt: "2026-02-25",
    comments:
      "Airport meal that does not feel like a fallback. Good before evening flights.",
  },
  {
    id: "bt-maxwell-curry-puff",
    placeName: "Maxwell Curry Puff",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.28062,
    longitude: 103.84452,
    neighborhood: "Maxwell",
    costPerPerson: 2.8,
    currency: "SGD",
    cuisineGenre: "hawker",
    itemsBought: "Chicken curry puff",
    ratingOutOf10: 7,
    visitedAt: "2026-05-21",
    comments:
      "Crisp pastry and a useful snack when the main queue is too long.",
  },
  {
    id: "bt-maxwell-tofu",
    placeName: "Maxwell Beancurd Stall",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.28072,
    longitude: 103.84458,
    neighborhood: "Maxwell",
    costPerPerson: 3.5,
    currency: "SGD",
    cuisineGenre: "dessert",
    itemsBought: "Soy beancurd, grass jelly",
    ratingOutOf10: 7,
    visitedAt: "2026-05-12",
    comments: "Light dessert after lunch, with a good balance of sweetness.",
  },
  {
    id: "bt-bugis-nasi-lemak",
    placeName: "Bugis Nasi Lemak",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.30073,
    longitude: 103.85438,
    neighborhood: "Bugis",
    costPerPerson: 8.5,
    currency: "SGD",
    cuisineGenre: "hawker",
    itemsBought: "Nasi lemak, fried chicken, egg",
    ratingOutOf10: 8,
    visitedAt: "2026-04-11",
    comments: "Good sambal and a satisfying portion for a quick dinner.",
  },
  {
    id: "bt-bugis-korean-bbq",
    placeName: "Bugis Korean Grill",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.30076,
    longitude: 103.85442,
    neighborhood: "Bugis",
    costPerPerson: 28,
    currency: "SGD",
    cuisineGenre: "Korean",
    itemsBought: "Pork belly set, rice, banchan",
    ratingOutOf10: 9,
    visitedAt: "2026-04-06",
    comments:
      "A louder dinner, but the meat quality and side dishes were worth it.",
  },
  {
    id: "bt-bugis-matcha-cafe",
    placeName: "Bugis Matcha Room",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.30078,
    longitude: 103.85445,
    neighborhood: "Bugis",
    costPerPerson: 14,
    currency: "SGD",
    cuisineGenre: "cafe",
    itemsBought: "Matcha latte, toast",
    ratingOutOf10: 7,
    visitedAt: "2026-03-30",
    comments: "Quiet enough for a catch-up and not overly sweet.",
  },
  {
    id: "bt-bugis-fried-chicken",
    placeName: "Bugis Fried Chicken Counter",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.30075,
    longitude: 103.8544,
    neighborhood: "Bugis",
    costPerPerson: 11,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Crispy chicken burger, fries",
    ratingOutOf10: 8,
    visitedAt: "2026-03-19",
    comments:
      "Crunchy and convenient. The fries are better while they are fresh.",
  },
  {
    id: "bt-orchard-burger",
    placeName: "Orchard Smash Burger",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.30491,
    longitude: 103.83184,
    neighborhood: "Orchard",
    costPerPerson: 18,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Double smash burger, fries",
    ratingOutOf10: 8,
    visitedAt: "2026-03-12",
    comments: "Messy in the right way and quick enough for a shopping break.",
  },
  {
    id: "bt-orchard-sushi",
    placeName: "Orchard Sushi Counter",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.30526,
    longitude: 103.83214,
    neighborhood: "Orchard",
    costPerPerson: 32,
    currency: "SGD",
    cuisineGenre: "Japanese",
    itemsBought: "Salmon don, miso soup",
    ratingOutOf10: 9,
    visitedAt: "2026-02-14",
    comments: "Fresh fish and a calmer meal after a busy afternoon.",
  },
  {
    id: "bt-novena-thai",
    placeName: "Novena Thai Kitchen",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.32021,
    longitude: 103.84462,
    neighborhood: "Novena",
    costPerPerson: 17,
    currency: "SGD",
    cuisineGenre: "Thai",
    itemsBought: "Pad kra pao, mango sticky rice",
    ratingOutOf10: 8,
    visitedAt: "2026-02-05",
    comments: "Good heat level and a dependable lunch set.",
  },
  {
    id: "bt-novena-seafood",
    placeName: "Novena Seafood House",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.32058,
    longitude: 103.84483,
    neighborhood: "Novena",
    costPerPerson: 36,
    currency: "SGD",
    cuisineGenre: "seafood",
    itemsBought: "Salted egg prawns, fried rice",
    ratingOutOf10: 7,
    visitedAt: "2026-01-28",
    comments: "Better for sharing than solo dining, with generous portions.",
  },
  {
    id: "bt-chinatown-indian",
    placeName: "Chinatown Banana Leaf",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.28354,
    longitude: 103.84519,
    neighborhood: "Chinatown",
    costPerPerson: 13,
    currency: "SGD",
    cuisineGenre: "Indian",
    itemsBought: "Fish curry, naan, papadum",
    ratingOutOf10: 9,
    visitedAt: "2026-01-17",
    comments: "Strong spices and a good weekday value meal.",
  },
  {
    id: "bt-chinatown-cafe",
    placeName: "Chinatown Window Cafe",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.28382,
    longitude: 103.84544,
    neighborhood: "Chinatown",
    costPerPerson: 12,
    currency: "SGD",
    cuisineGenre: "cafe",
    itemsBought: "Long black, kaya toast",
    ratingOutOf10: 8,
    visitedAt: "2026-01-10",
    comments: "Small space with a pleasant view of the street below.",
  },
  {
    id: "bt-marina-western",
    placeName: "Marina Western Table",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.29013,
    longitude: 103.85734,
    neighborhood: "Marina Bay",
    costPerPerson: 42,
    currency: "SGD",
    cuisineGenre: "western",
    itemsBought: "Steak frites, sparkling water",
    ratingOutOf10: 8,
    visitedAt: "2025-12-22",
    comments:
      "A special-occasion entry with a view that carries part of the price.",
  },
  {
    id: "bt-marina-dessert",
    placeName: "Marina Citrus Bar",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.29035,
    longitude: 103.85751,
    neighborhood: "Marina Bay",
    costPerPerson: 16,
    currency: "SGD",
    cuisineGenre: "dessert",
    itemsBought: "Citrus tart, tea",
    ratingOutOf10: 8,
    visitedAt: "2025-12-20",
    comments: "Bright dessert and a good place to slow down after dinner.",
  },
  {
    id: "bt-tampines-korean",
    placeName: "Tampines Korean Rice Bowl",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.35393,
    longitude: 103.94414,
    neighborhood: "Tampines",
    costPerPerson: 12,
    currency: "SGD",
    cuisineGenre: "Korean",
    itemsBought: "Beef bulgogi bowl, kimchi",
    ratingOutOf10: 7,
    visitedAt: "2025-12-10",
    comments: "Fast service and a filling bowl for a workday lunch.",
  },
  {
    id: "bt-tampines-fast-food",
    placeName: "Tampines Chicken Shack",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.35421,
    longitude: 103.94438,
    neighborhood: "Tampines",
    costPerPerson: 10,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Chicken tenders, lemonade",
    ratingOutOf10: 7,
    visitedAt: "2025-11-28",
    comments: "Comfortable casual option when everyone wants something easy.",
  },
  {
    id: "bt-jurong-western",
    placeName: "Jurong Sunday Roast",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.33481,
    longitude: 103.74219,
    neighborhood: "Jurong East",
    costPerPerson: 25,
    currency: "SGD",
    cuisineGenre: "western",
    itemsBought: "Roast chicken, vegetables",
    ratingOutOf10: 8,
    visitedAt: "2025-11-16",
    comments: "Comforting portion sizes and a relaxed weekend atmosphere.",
  },
  {
    id: "bt-jurong-dessert",
    placeName: "Jurong Ice Kacang",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.33506,
    longitude: 103.74242,
    neighborhood: "Jurong East",
    costPerPerson: 5,
    currency: "SGD",
    cuisineGenre: "dessert",
    itemsBought: "Ice kacang, chendol",
    ratingOutOf10: 8,
    visitedAt: "2025-11-09",
    comments:
      "Cold, sweet, and exactly what was needed after walking around the mall.",
  },
  {
    id: "bt-bedok-hawker-one",
    placeName: "Bedok Hawker Laksa",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.32412,
    longitude: 103.93031,
    neighborhood: "Bedok",
    costPerPerson: 6,
    currency: "SGD",
    cuisineGenre: "hawker",
    itemsBought: "Katong laksa",
    ratingOutOf10: 9,
    visitedAt: "2025-10-25",
    comments: "A spicy, rich bowl that is worth returning for.",
  },
  {
    id: "bt-bedok-hawker-two",
    placeName: "Bedok Char Kway Teow",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.32414,
    longitude: 103.93033,
    neighborhood: "Bedok",
    costPerPerson: 5.5,
    currency: "SGD",
    cuisineGenre: "hawker",
    itemsBought: "Char kway teow, lime juice",
    ratingOutOf10: 8,
    visitedAt: "2025-10-18",
    comments: "Smoky wok flavour and a generous serving for the price.",
  },
  {
    id: "bt-bedok-hawker-three",
    placeName: "Bedok Oyster Omelette",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.32413,
    longitude: 103.93032,
    neighborhood: "Bedok",
    costPerPerson: 8,
    currency: "SGD",
    cuisineGenre: "seafood",
    itemsBought: "Oyster omelette",
    ratingOutOf10: 7,
    visitedAt: "2025-10-11",
    comments: "Crispy edges and a useful shared side for the table.",
  },
  {
    id: "bt-one-north-western",
    placeName: "One-North Pasta Desk",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.29972,
    longitude: 103.78791,
    neighborhood: "one-north",
    costPerPerson: 19,
    currency: "SGD",
    cuisineGenre: "western",
    itemsBought: "Pesto pasta, iced lemon tea",
    ratingOutOf10: 8,
    visitedAt: "2025-09-30",
    comments: "Reliable office lunch with enough seating for a small group.",
  },
  {
    id: "bt-one-north-cafe",
    placeName: "One-North Coffee Lab",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.29994,
    longitude: 103.78812,
    neighborhood: "one-north",
    costPerPerson: 9,
    currency: "SGD",
    cuisineGenre: "cafe",
    itemsBought: "Cold brew, banana bread",
    ratingOutOf10: 8,
    visitedAt: "2025-09-22",
    comments: "Good coffee and a convenient stop between meetings.",
  },
  {
    id: "bt-clarke-thai",
    placeName: "Clarke Quay Thai Table",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.28955,
    longitude: 103.84662,
    neighborhood: "Clarke Quay",
    costPerPerson: 24,
    currency: "SGD",
    cuisineGenre: "Thai",
    itemsBought: "Tom yum, basil chicken, rice",
    ratingOutOf10: 8,
    visitedAt: "2025-09-14",
    comments:
      "Good for sharing, though the riverside location makes it busier at night.",
  },
  {
    id: "bt-clarke-fast-food",
    placeName: "Clarke Quay Late Bite",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.28982,
    longitude: 103.84684,
    neighborhood: "Clarke Quay",
    costPerPerson: 9,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Loaded fries, soft drink",
    ratingOutOf10: 6,
    visitedAt: "2025-09-06",
    comments: "Convenient after a late evening, but not a destination meal.",
  },
  {
    id: "bt-bukit-timah-indian",
    placeName: "Bukit Timah Roti Table",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.32911,
    longitude: 103.80211,
    neighborhood: "Bukit Timah",
    costPerPerson: 10,
    currency: "SGD",
    cuisineGenre: "Indian",
    itemsBought: "Roti prata, mutton curry",
    ratingOutOf10: 9,
    visitedAt: "2025-08-29",
    comments: "Crisp prata and a curry with enough depth to share.",
  },
  {
    id: "bt-bukit-timah-cafe",
    placeName: "Bukit Timah Garden Cafe",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.32934,
    longitude: 103.80235,
    neighborhood: "Bukit Timah",
    costPerPerson: 15,
    currency: "SGD",
    cuisineGenre: "cafe",
    itemsBought: "Avocado toast, flat white",
    ratingOutOf10: 7,
    visitedAt: "2025-08-21",
    comments: "Pleasant greenery and a slower breakfast pace.",
  },
  {
    id: "bt-botanic-indestructible-one",
    placeName: "Botanic Garden Bento",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.313001,
    longitude: 103.815001,
    neighborhood: "Botanic Gardens",
    costPerPerson: 14,
    currency: "SGD",
    cuisineGenre: "Japanese",
    itemsBought: "Salmon bento",
    ratingOutOf10: 8,
    visitedAt: "2025-08-12",
    comments: "A practical picnic meal before walking through the gardens.",
  },
  {
    id: "bt-botanic-indestructible-two",
    placeName: "Botanic Garden Sandwiches",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.3130012,
    longitude: 103.8150012,
    neighborhood: "Botanic Gardens",
    costPerPerson: 13,
    currency: "SGD",
    cuisineGenre: "western",
    itemsBought: "Chicken sandwich, iced tea",
    ratingOutOf10: 7,
    visitedAt: "2025-08-07",
    comments: "Simple food that travels well for a long afternoon outside.",
  },
  {
    id: "bt-botanic-indestructible-three",
    placeName: "Botanic Garden Mochi",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.3130013,
    longitude: 103.8150011,
    neighborhood: "Botanic Gardens",
    costPerPerson: 6,
    currency: "SGD",
    cuisineGenre: "dessert",
    itemsBought: "Mochi assortment",
    ratingOutOf10: 8,
    visitedAt: "2025-08-05",
    comments: "Small, neat dessert bites for sharing after the walk.",
  },
  {
    id: "bt-botanic-indestructible-four",
    placeName: "Botanic Garden Tea House",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.3130008,
    longitude: 103.8150013,
    neighborhood: "Botanic Gardens",
    costPerPerson: 11,
    currency: "SGD",
    cuisineGenre: "cafe",
    itemsBought: "Earl Grey, scone",
    ratingOutOf10: 8,
    visitedAt: "2025-07-29",
    comments:
      "A calm final stop and a good example of a location with several saved entries.",
  },
  {
    id: "bt-chinatown-dumplings-priya",
    placeName: "Chinatown Dumpling House",
    ownerName: "Priya",
    ownerKind: "friend",
    latitude: 1.2834,
    longitude: 103.8437,
    neighborhood: "Chinatown",
    costPerPerson: 16,
    currency: "SGD",
    cuisineGenre: "Chinese",
    itemsBought: "Pork dumplings, tea",
    ratingOutOf10: 8,
    visitedAt: "2025-07-16",
    comments: "A generous dumpling basket and a useful group dinner option.",
  },
  {
    id: "bt-chinatown-noodles-daniel",
    placeName: "South Bridge Noodle Bar",
    ownerName: "Daniel",
    ownerKind: "friend",
    latitude: 1.2838,
    longitude: 103.8442,
    neighborhood: "Chinatown",
    costPerPerson: 12,
    currency: "SGD",
    cuisineGenre: "Chinese",
    itemsBought: "Beef noodles",
    ratingOutOf10: 7,
    visitedAt: "2025-07-11",
    comments:
      "Quick noodles with a rich broth and plenty of chili on the side.",
  },
  {
    id: "bt-kampong-glam-malay-aisha",
    placeName: "Kampong Glam Heritage Kitchen",
    ownerName: "Aisha",
    ownerKind: "friend",
    latitude: 1.3029,
    longitude: 103.8598,
    neighborhood: "Kampong Glam",
    costPerPerson: 14,
    currency: "SGD",
    cuisineGenre: "Malay",
    itemsBought: "Nasi ambeng, iced bandung",
    ratingOutOf10: 9,
    visitedAt: "2025-06-28",
    comments:
      "Excellent shared platter for a larger table and a relaxed evening.",
  },
  {
    id: "bt-kampong-glam-cafe-lucas",
    placeName: "Arab Street Courtyard",
    ownerName: "Lucas",
    ownerKind: "friend",
    latitude: 1.3034,
    longitude: 103.8589,
    neighborhood: "Kampong Glam",
    costPerPerson: 18,
    currency: "SGD",
    cuisineGenre: "Others",
    itemsBought: "Shakshuka, mint tea",
    ratingOutOf10: 8,
    visitedAt: "2025-06-22",
    comments:
      "Good courtyard atmosphere and an easy place to linger after dinner.",
  },
  {
    id: "bt-orchard-fast-food-chloe",
    placeName: "Orchard Crispy Chicken",
    ownerName: "Chloe",
    ownerKind: "friend",
    latitude: 1.3041,
    longitude: 103.8318,
    neighborhood: "Orchard",
    costPerPerson: 11,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Chicken burger, fries",
    ratingOutOf10: 6,
    visitedAt: "2025-06-13",
    comments:
      "Reliable shopping break when convenience matters more than novelty.",
  },
  {
    id: "bt-orchard-dessert-ethan",
    placeName: "Orchard Snow Dessert",
    ownerName: "Ethan",
    ownerKind: "friend",
    latitude: 1.3045,
    longitude: 103.8324,
    neighborhood: "Orchard",
    costPerPerson: 9,
    currency: "SGD",
    cuisineGenre: "dessert",
    itemsBought: "Mango shaved ice",
    ratingOutOf10: 7,
    visitedAt: "2025-06-09",
    comments:
      "Refreshing dessert stop with enough portion for two people to share.",
  },
  {
    id: "bt-tiong-bahru-chinese-sofia",
    placeName: "Tiong Bahru Roast Corner",
    ownerName: "Sofia",
    ownerKind: "friend",
    latitude: 1.2862,
    longitude: 103.8271,
    neighborhood: "Tiong Bahru",
    costPerPerson: 13,
    currency: "SGD",
    cuisineGenre: "Chinese",
    itemsBought: "Roast duck rice",
    ratingOutOf10: 8,
    visitedAt: "2025-05-31",
    comments:
      "Crisp skin, quick service, and a good lunch option around the estate.",
  },
  {
    id: "bt-tiong-bahru-cafe-jun",
    placeName: "Brick Lane Coffee Room",
    ownerName: "Jun",
    ownerKind: "friend",
    latitude: 1.2858,
    longitude: 103.8277,
    neighborhood: "Tiong Bahru",
    costPerPerson: 17,
    currency: "SGD",
    cuisineGenre: "cafe",
    itemsBought: "Toastie, long black",
    ratingOutOf10: 8,
    visitedAt: "2025-05-24",
    comments: "Quiet weekday cafe with a compact menu and good coffee.",
  },
  {
    id: "bt-paya-lebar-malay-farah",
    placeName: "Paya Lebar Sambal Table",
    ownerName: "Farah",
    ownerKind: "friend",
    latitude: 1.3177,
    longitude: 103.8925,
    neighborhood: "Paya Lebar",
    costPerPerson: 10,
    currency: "SGD",
    cuisineGenre: "Malay",
    itemsBought: "Ayam penyet, teh tarik",
    ratingOutOf10: 8,
    visitedAt: "2025-05-17",
    comments: "Spicy and filling with a useful range of rice dishes.",
  },
  {
    id: "bt-paya-lebar-korean-marcus",
    placeName: "Eastside Korean Grill",
    ownerName: "Marcus",
    ownerKind: "friend",
    latitude: 1.3182,
    longitude: 103.8931,
    neighborhood: "Paya Lebar",
    costPerPerson: 29,
    currency: "SGD",
    cuisineGenre: "Korean",
    itemsBought: "Pork belly, kimchi stew",
    ratingOutOf10: 9,
    visitedAt: "2025-05-10",
    comments: "Worth the higher spend for a proper shared grill meal.",
  },
  {
    id: "bt-jurong-seafood-rachel",
    placeName: "Jurong Seafood Wok",
    ownerName: "Rachel",
    ownerKind: "friend",
    latitude: 1.3331,
    longitude: 103.7435,
    neighborhood: "Jurong East",
    costPerPerson: 24,
    currency: "SGD",
    cuisineGenre: "seafood",
    itemsBought: "Salted egg prawns, rice",
    ratingOutOf10: 8,
    visitedAt: "2025-04-26",
    comments:
      "A good family-style option when several dishes are being shared.",
  },
  {
    id: "bt-jurong-western-nabil",
    placeName: "Westside Grill Plate",
    ownerName: "Nabil",
    ownerKind: "friend",
    latitude: 1.3337,
    longitude: 103.7429,
    neighborhood: "Jurong East",
    costPerPerson: 21,
    currency: "SGD",
    cuisineGenre: "western",
    itemsBought: "Steak, mushroom sauce",
    ratingOutOf10: 7,
    visitedAt: "2025-04-19",
    comments: "Straightforward western comfort food with generous sides.",
  },
  {
    id: "bt-serangoon-thai-olivia",
    placeName: "Serangoon Lime Leaf",
    ownerName: "Olivia",
    ownerKind: "friend",
    latitude: 1.3507,
    longitude: 103.8722,
    neighborhood: "Serangoon",
    costPerPerson: 19,
    currency: "SGD",
    cuisineGenre: "Thai",
    itemsBought: "Tom yum, basil chicken",
    ratingOutOf10: 8,
    visitedAt: "2025-04-12",
    comments: "Bright flavors and a convenient dinner option near the station.",
  },
  {
    id: "bt-serangoon-other-hannah",
    placeName: "Serangoon Mezze Room",
    ownerName: "Hannah",
    ownerKind: "friend",
    latitude: 1.3512,
    longitude: 103.8716,
    neighborhood: "Serangoon",
    costPerPerson: 23,
    currency: "SGD",
    cuisineGenre: "Others",
    itemsBought: "Hummus platter, grilled halloumi",
    ratingOutOf10: 9,
    visitedAt: "2025-04-06",
    comments:
      "Excellent sharing menu and a useful non-Asian option for groups.",
  },
  {
    id: "bt-shiok-burger-garlic-chicken",
    placeId: "bt-place-shiok-burger-hillion",
    placeName: "Shiok Burger",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.3776,
    longitude: 103.7718,
    neighborhood: "Hillion Mall",
    costPerPerson: 10,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Classic Garlic Chicken Burger set",
    ratingOutOf10: 10,
    visitedAt: "2026-07-10",
    comments:
      "Crispy chicken and a strong garlic sauce. The set was worth the price.",
  },
  {
    id: "bt-shiok-burger-shin-mala",
    placeId: "bt-place-shiok-burger-hillion",
    placeName: "Shiok Burger",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.3776,
    longitude: 103.7718,
    neighborhood: "Hillion Mall",
    costPerPerson: 12,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Shin Mala Burger",
    ratingOutOf10: 6,
    visitedAt: "2026-07-11",
    comments:
      "The mala flavor was interesting, but the spice overwhelmed the burger.",
  },
  {
    id: "bt-wingstop-hillion-benny-1",
    placeId: "bt-place-wingstop-hillion",
    placeName: "Wingstop",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.3779,
    longitude: 103.7721,
    neighborhood: "Hillion Mall",
    costPerPerson: 8,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Classic wings, fries",
    ratingOutOf10: 4,
    visitedAt: "2026-07-09",
    comments: "The wings were fine, but the meal felt too salty on this visit.",
  },
  {
    id: "bt-wingstop-hillion-benny-2",
    placeId: "bt-place-wingstop-hillion",
    placeName: "Wingstop",
    ownerName: "Jordan",
    ownerKind: "friend",
    latitude: 1.3779,
    longitude: 103.7721,
    neighborhood: "Hillion Mall",
    costPerPerson: 9,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Spicy wings, coleslaw",
    ratingOutOf10: 5,
    visitedAt: "2026-06-26",
    comments:
      "Better sauce choice than the first visit, but still an average stop.",
  },
  {
    id: "bt-wingstop-hillion-kai-1",
    placeId: "bt-place-wingstop-hillion",
    placeName: "Wingstop",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.3779,
    longitude: 103.7721,
    neighborhood: "Hillion Mall",
    costPerPerson: 10,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Garlic parmesan wings, drink",
    ratingOutOf10: 6,
    visitedAt: "2026-06-15",
    comments: "Decent wings and a convenient option after shopping.",
  },
  {
    id: "bt-wingstop-hillion-kai-2",
    placeId: "bt-place-wingstop-hillion",
    placeName: "Wingstop",
    ownerName: "Kai",
    ownerKind: "friend",
    latitude: 1.3779,
    longitude: 103.7721,
    neighborhood: "Hillion Mall",
    costPerPerson: 11,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Boneless wings, fries",
    ratingOutOf10: 7,
    visitedAt: "2026-05-30",
    comments: "More enjoyable with the boneless option and a milder sauce.",
  },
  {
    id: "bt-wingstop-hillion-mira-1",
    placeId: "bt-place-wingstop-hillion",
    placeName: "Wingstop",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.3779,
    longitude: 103.7721,
    neighborhood: "Hillion Mall",
    costPerPerson: 12,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Louisiana rub wings, rice",
    ratingOutOf10: 8,
    visitedAt: "2026-05-12",
    comments:
      "The seasoning was balanced and the portion felt fair for the price.",
  },
  {
    id: "bt-wingstop-hillion-mira-2",
    placeId: "bt-place-wingstop-hillion",
    placeName: "Wingstop",
    ownerName: "Mira",
    ownerKind: "friend",
    latitude: 1.3779,
    longitude: 103.7721,
    neighborhood: "Hillion Mall",
    costPerPerson: 13,
    currency: "SGD",
    cuisineGenre: "fast food",
    itemsBought: "Honey mustard wings, loaded fries",
    ratingOutOf10: 9,
    visitedAt: "2026-04-28",
    comments:
      "The strongest visit in this sample set, especially with the loaded fries.",
  },
];

// Mock records are always friend records. They are only appended by the map
// adapter and must never appear in friends-list/profile state.
export const mockFoodEntries: BiteTrailFoodEntry[] = rawMockFoodEntries.map(
  (entry) => ({
    ...entry,
    ownerKind: "friend",
    ownerName: entry.ownerName,
  }),
);

const getPlaceId = (entry: BiteTrailFoodEntry) => entry.placeId ?? entry.id;

export const mockFoodPlaces: BiteTrailPlace[] = Array.from(
  mockFoodEntries.reduce((groups, entry) => {
    const placeId = getPlaceId(entry);
    const visits = groups.get(placeId) ?? [];
    visits.push(entry);
    groups.set(placeId, visits);
    return groups;
  }, new Map<string, BiteTrailFoodEntry[]>()),
).map(([id, visits]) => {
  const firstVisit = visits[0];
  return {
    averageCost:
      visits.reduce((total, visit) => total + visit.costPerPerson, 0) /
      visits.length,
    averageRating:
      visits.reduce((total, visit) => total + visit.ratingOutOf10, 0) /
      visits.length,
    cuisineGenre: firstVisit.cuisineGenre,
    currency: firstVisit.currency,
    id,
    latitude: firstVisit.latitude,
    longitude: firstVisit.longitude,
    neighborhood: firstVisit.neighborhood,
    placeName: firstVisit.placeName,
    visits,
  };
});
